spring:
  application:
    name: ai_code_helper
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-6576d96f347b4805a8ea620188763945
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-6576d96f347b4805a8ea620188763945
      streaming-chat-model:
        model-name: qwen-max
        api-key: sk-6576d96f347b4805a8ea620188763945
bigmodel:
  api-key: 238843ebc8674b61a780f7fff7a6fa3a.g2jGbt977gWbhPOO